# This is a config for E2B sandbox template.
# You can use template ID (z206elgrdtwry7i86irk) or template name (zexil-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("zexil-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("zexil-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('zexil-nextjs')

team_id = "7b3161df-3283-47fc-8590-12e698c74ce5"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "zexil-nextjs"
template_id = "z206elgrdtwry7i86irk"
